### ISSUE TITLE
Prepare Gazebo+YARP(+ROS2)-enabled Docker image

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/teo-gazebo-models#10]
Gazebo 11 (i.e. Gazebo Classic) [reached its end of life](https://community.gazebosim.org/t/gazebo-classic-end-of-life/2563) and thus no more releases nor support are expected. In fact, Ubuntu 24.04 (Noble) lacks an apt package. This issue aims to document the creation of a Docker image based on Ubuntu 22.04 providing the following stack:

- Gazebo 11
- latest stable YARP (3.9 ATOW)
- [gazebo-yarp-plugins](https://github.com/robotology/gazebo-yarp-plugins)
- (optionally) pre-installed teo-gazebo-models

**Comment by PeterBowman** [comment]
This is already WIP, commit https://github.com/roboticslab-uc3m/teo-gazebo-models/commit/821916ad487dc57036aae5c6997fd47258dae28f did most of the work. It is important to note that this image does not aim to provide developer packages, only production binaries. For that reason, *-dev packages that had been installed in order to build stuff were purged from the final image to reduce space:

https://github.com/roboticslab-uc3m/teo-gazebo-models/blob/821916ad487dc57036aae5c6997fd47258dae28f/docker/Dockerfile#L6-L32

Without `apt-get purge -y $DEV_PACKAGES` and the subsequent `apt autopurge`, the overall image size raise from about 1 GB up to 2.5 GB or so.

**Comment by PeterBowman** [comment]
Regarding YARP communications between container and host, I had a hard time to make this work due to not realizing that [Rootless Docker](https://docs.docker.com/engine/security/rootless/) prevents from properly doing IPC. I just had to switch to using [Docker as a non-sudo user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) and it worked automatically (see https://github.com/robotology/yarp/discussions/3124).

For the record, YARP already provides a Docker image and its instructions for use:

- [Dockerfile](https://github.com/robotology/yarp/blob/bde9cd2b1069d207a77a845935b2c3063c74c58d/docker/Dockerfile)
- https://yarp.it/git-master/yarp_docker.html
- `sudo docker run --rm -it --privileged --network host --pid host -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /etc/hosts:/etc/hosts -e QT_X11_NO_MITSHM=1 yarp:ubuntu22.04`
   - to enable GUIs: `sudo xhost +`

In my experiments, the image I am setting up does not even need `--network host` (the default entrypoint is the `gazebo` executable). A volume is mounted to share the directory `yarp conf` points at:

```bash
docker run --rm -it --entrypoint /bin/bash \
            -v ${HOME}/.config/yarp/:/root/.config/yarp/:ro
            teo-gazebo-models
```

**Comment by PeterBowman** [comment]
Regarding Gazebo, there is a quite noticeable loading time on first use. This is caused by Gazebo downloading an initial collection of models (namely "ground_plane" and "sun"). In commit https://github.com/roboticslab-uc3m/teo-gazebo-models/commit/e44a1ffad2609b9d0146720c6914dfec730ad003, a gazebo_models.txt file is copied into the image containing the download URLs for said models, and they are extracted into `~/.gazebo/models/` during the build phase. This solution was borrowed from https://stackoverflow.com/a/66979517:

```bash
mkdir -p ~/.gazebo/models
wget -i gazebo_models.txt
ls model.tar.gz* | xargs -n 1 sh -c 'tar xzvf "$@" -C ~/.gazebo/models/' dummy
```

The package download list is hosted at http://file.ncnynl.com/ros/gazebo_models.txt ([backup](https://github.com/user-attachments/files/16467177/gazebo_models_all.txt)). Note the full list of models takes more than 300 MB.

However, ~~I reverted said commit and~~ chose to mount `$HOME/.gazebo/models/` on each container. In this way, the annoying but somewhat accepted Gazebo behavior is preserved, any additional downloaded models are stored in the host and all these are shared by any subsequently created container.

So far, the invocation looks like this:

```bash
docker run --rm -it --entrypoint /bin/bash \
            -v ${HOME}/.config/yarp/:/root/.config/yarp/:ro \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -v ${HOME}/.gazebo/models/:/root/.gazebo/models/ \
            -e DISPLAY \
            teo-gazebo-models
```

Alternatively, models can be persisted using Docker volumes:

```bash
docker volume create --name gazebo_models
docker run ... -v gazebo_models:/root/.gazebo/models/
```

Note it is mandatory to run `sudo xhost +` at least once per session before issuing the `docker run` command.

Edit: I did not revert the commit since both scenarios can coexist. If the `-v` option is omitted, Gazebo will fetch the models locally stored in the container's models path. Otherwise, it will use the model path of the host, and populate it on the first launch if it's empty.

**Comment by PeterBowman** [comment]
For some reason I don't quite get yet, Gazebo is *slow* if the `--privileged` option to `docker run` is omitted. Also, the following additional output is shown upon running Gazebo (along with more lines related to ALSA):

```
MESA: error: Failed to query drm device.
libGL error: glx: failed to create dri3 screen
libGL error: failed to load driver: iris
libGL error: failed to open /dev/dri/card1: No such file or directory
```

I presume the `--privileged` option enables hardware acceleration. Besides, the Gazebo viewer looks a bit different without it (kinda brighter).

**Comment by PeterBowman** [comment]
I decided to take advantage of [multi-stage builds](https://docs.docker.com/build/building/multi-stage/) in https://github.com/roboticslab-uc3m/teo-gazebo-models/commit/bdab8bbc7f876796db483d512ad58dac68a33e77. Previously, a single looong `RUN` instruction was used in which any file installed/built/created and deemed temporary was later removed (this is recommended in order to decrease image size):

```dockerfile
RUN apt-update && apt-install -y $LIST_OF_DEVELOPMENT_PACKAGES && \
    build-project-a && \
    build-project-b && \
    build-project-c && \
    apt-get purge -y $LIST_OF_DEVELOPMENT_PACKAGES && \
    other-cleanup-instructions
```

Instead of that, the Dockerfile was split into a build stage and the final stage. The former is dismissed in the final image, and the latter copies any resulting binaries from it. Besides, it is no longer necessary to maintain a single an unwieldy `RUN` in the build stage, nor to take care of cleaning intermediate files (https://github.com/roboticslab-uc3m/teo-gazebo-models/commit/5831a6f41ae770df7f00b58e411d7d3496d7a843):

```dockerfile
FROM base_image AS build

RUN apt-get update && apt-get install -y $LIST_OF_DEVELOPMENT_PACKAGES

RUN build-project-a
RUN build-project-b
RUN build-project-c

FROM final_image
COPY --from=build /binaries /usr/local

RUN whatever
```

**Comment by PeterBowman** [comment]
I am also preparing a variant image for with ROS2 support: https://github.com/roboticslab-uc3m/teo-gazebo-models/commit/a46940c69878ed63151504220fd24ba5c80c1bd6. Official base ROS images are detailed [here](https://github.com/docker-library/docs/tree/master/ros), the following ones are relevant for our use case (see [description](https://github.com/docker-library/docs/tree/6bcd09328e5a337f20e62f30e06833831265bb0b/ros)):

- [humble-ros-core-jammy](https://github.com/osrf/docker_images/blob/27cc0b68263bbbb10bb58dd814efc0a6b0a01ec7/ros/humble/ubuntu/jammy/ros-core/Dockerfile): minimal ROS install (comms)
- [humble-ros-base-jammy](https://github.com/osrf/docker_images/blob/20e3ba685bb353a3c00be9ba01c1b7a6823c9472/ros/humble/ubuntu/jammy/ros-base/Dockerfile): ros-core + build tools

At first, I tried to pull ros-base for the build stage, then prepare the final image with ros-core. However, the following exception was showing up upon `ros2 topic echo`:

```
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.10', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 91, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/command/topic.py", line 41, in main
    return extension.main(args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/verb/echo.py", line 220, in main
    qos_profile = self.choose_qos(node, args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/verb/echo.py", line 146, in choose_qos
    pubs_info = node.get_publishers_info_by_topic(args.topic_name)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1348, in parse_response
    p.feed(data)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 451, in feed
    self._parser.Parse(data, False)
  File "../Modules/pyexpat.c", line 416, in StartElement
  File "/usr/lib/python3.10/xmlrpc/client.py", line 689, in start
    raise ResponseError("unknown tag %r" % tag)
xmlrpc.client.ResponseError: ResponseError("unknown tag 'rclpy.type_hash.TypeHash'")
```

I realized this is caused by some missing package. For that reason, both build stages pull from ros-base at the cost of a slight increase in the image size.

Also note that yarp-devices-ros2 requires the `ros-humble-test-msgs` apt package.

**Comment by PeterBowman** [comment]
A specific YARP tag can be passed to the builder via `--build-arg YARP_TAG=...` to choose a specific branch/commit/tag. I noticed that YARP plugins can't be found if building on the yarp-3.9 branch, whereas the master branch succeeds. This has been verified both locally and via GHA builds (I have already removed the faulty images). The following command allowed me to capture the structure of the `/usr/local` directory and compare both branches:

`docker run --rm --privileged --entrypoint "/bin/bash" --network host -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.config/yarp:/root/.config/yarp:ro -e DISPLAY teo-gm2 -c "apt-get update && apt-get install -y tree && tree /usr/local" > test.txt`

However, I see nothing suspicious. No clue what the culprit could be.

**Comment by PeterBowman** [comment]
> At first, I tried to pull ros-base for the build stage, then prepare the final image with ros-core. However, the following exception was showing up upon `ros2 topic echo`:

> I realized this is caused by some missing package. For that reason, both build stages pull from ros-base at the cost of a slight increase in the image size.

Actually, I managed to communicate successfully between host and container using humble-ros-core. Not sure yet, perhaps removing `--network host` helped. I have replaced the images at ghcr.io.

Anyway, establishing correct comms seems a bit random. If a `ros2 topic echo` shows no output, re-run the image and try again.

**Comment by PeterBowman** [comment]
Done: [Docker build files](https://github.com/roboticslab-uc3m/teo-gazebo-models/tree/master/docker) ([permalink](https://github.com/roboticslab-uc3m/teo-gazebo-models/tree/fdbac3e3560c9659188cfdf6d7188e4180301765/docker)), [GH Actions workflow](https://github.com/roboticslab-uc3m/teo-gazebo-models/blob/master/.github/workflows/docker.yml) ([permalink](https://github.com/roboticslab-uc3m/teo-gazebo-models/blob/fdbac3e3560c9659188cfdf6d7188e4180301765/.github/workflows/docker.yml), [actions tab](https://github.com/roboticslab-uc3m/teo-gazebo-models/actions/workflows/docker.yml)).

cc @roboticslab-uc3m/teo New Docker images are available providing Gazebo + YARP + TEO models (an extra image was also added for interfacing via ROS2). This aims to overcome the lack of official Gazebo packages in Ubuntu 24.04. See [instructions for use](https://github.com/roboticslab-uc3m/teo-gazebo-models/pkgs/container/teo-gazebo-models#docker).

Soon, I'll try to generate a similar image for OpenRAVE + YARP + [models](https://github.com/roboticslab-uc3m/teo-openrave-models).

Edit: OpenRAVE image ready, see [package](https://github.com/roboticslab-uc3m/teo-openrave-models/pkgs/container/teo-openrave-models).
